/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dapur;

import Barista.BaristaModel;
import Koneksi.Koneksi;
import Login.LoginView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valer
 */
public class Dapur_View extends javax.swing.JFrame {

    /**
     * Creates new form Dapur_View
     */
    public Dapur_View() {
        initComponents();
        autorefresh();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(screenSize);
        DapurCon con = new DapurCon();
        Menu.setEditable(false);
        con.tampilkandatamakanan(dapur);
        startDurasiTimer(dapur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dapur = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Menu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setText("ORDER REPORT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ChatGPT Image 26 Mei 2025, 10.47.19 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(1693, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dapur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pesanan", "Nama Menu", "Qty"
            }
        ));
        dapur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dapurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dapur);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1460, 480));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 51));
        jButton2.setText("DONE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 540, 230, 45));

        Menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Menu.setText("Selected Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel4.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 1560, 620));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\valer\\Downloads\\tombol back.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 970, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel8.setText("ORDER STATUS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DapurCon con = new DapurCon();
        con.updatstatus(dapur);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    private void dapurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dapurMouseClicked
        int baris = dapur.getSelectedRow();
        if (baris < 11) {
            Menu.setText(dapur.getValueAt(baris, 1).toString());
            Menu.disable();
        }     
    }//GEN-LAST:event_dapurMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       LoginView v = new LoginView();
        v.show();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dapur_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dapur_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dapur_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dapur_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dapur_View().setVisible(true);
            }
        });
    }
    private void startDurasiTimer(JTable tabel) {
        Timer timer = new Timer(1000, e -> { //agar setiap 1 detik menjalankan fungsi timer
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                String statusMakanan = model.getValueAt(i, 5).toString();
                if (statusMakanan.equalsIgnoreCase("DONE")) {
                    // Kalau sudah DONE, durasi tidak diupdate, bisa dilewati
                    continue; 
                }
                String idPesanan = model.getValueAt(i, 0).toString(); 
                
                // Ambil timestamp dari database
                Timestamp waktuDipesan = null;
                try (Connection con = Koneksi.getConnection();
                     PreparedStatement ps = con.prepareStatement("SELECT tanggal FROM pesanan WHERE id_pesanan = ?")) {
                    ps.setString(1, idPesanan);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        waktuDipesan = rs.getTimestamp("tanggal");
                    }
                }

                if (waktuDipesan != null) {
                    long diff = System.currentTimeMillis() - waktuDipesan.getTime();//untuk menghitung selisih dari waktu dipesan
                    long menit = diff / 60000;//mengubah selisih waktu ke menit
                    long detik = (diff / 1000) % 60;// mengubah selisih ke detik
                    String durasi = String.format("%02dm %02ds", menit, detik);
                    model.setValueAt(durasi, i, 7); // kolom durasi
                } else {
                    model.setValueAt("N/A", i, 7);//jika waktu dipesan tidak ada maka tidak muncul.
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    });
    timer.start();
    }
    
    private void autorefresh(){
        Timer timer = new Timer(3000, e -> {
            DapurModel m = new DapurModel();
            DefaultTableModel model = m.getDataMakanan();
            dapur.setModel(model);
            dapur.getColumnModel().getColumn(6).setMinWidth(0);
            dapur.getColumnModel().getColumn(6).setMaxWidth(0);
            dapur.getColumnModel().getColumn(6).setWidth(0);
        });
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Menu;
    private javax.swing.JTable dapur;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
