/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Status_Kasir;

import Barista.BaristaModel;
import Dapur.DapurCon;
import Koneksi.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import pos_kasir.Pos_View;

/**
 *
 * @author ExpertBook
 */
public class StatusKasir_View extends javax.swing.JFrame {

    /**
     * Creates new form ViewStatus_Kasir
     */ 
    
    public JTable[] tables;
    public StatusKasir_View() {
        initComponents();   
        autorefresh();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(screenSize);
        StatusKasir_Con con = new StatusKasir_Con();
        con.tampilkandata(order);
        startDurasiTimer(order);
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        order = new javax.swing.JTable();
        done = new javax.swing.JButton();
        Menu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ChatGPT Image 26 Mei 2025, 10.47.19 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(1693, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(order);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1420, 570));

        done.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        done.setForeground(new java.awt.Color(0, 153, 51));
        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel4.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 610, 250, 45));

        Menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Menu.setText("Selected Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel4.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 250, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 1500, 690));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\valer\\Downloads\\tombol back.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 980, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("ORDER STATUS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        StatusKasir_Con con = new StatusKasir_Con();
        con.updatstatus(order);
    }//GEN-LAST:event_doneActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Pos_View v = new Pos_View();
        v.show();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
       
    }//GEN-LAST:event_MenuActionPerformed

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        int baris = order.getSelectedRow();
        if (baris < 11) {
            Menu.setText(order.getValueAt(baris, 2).toString());
            Menu.disable();
        }    
    }//GEN-LAST:event_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusKasir_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusKasir_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusKasir_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusKasir_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusKasir_View().setVisible(true);
            }
        });
    }
    private void startDurasiTimer(JTable tabel) {
        Timer timer = new Timer(1000, e -> {
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                String statusPesanan = model.getValueAt(i, 4).toString();
                if (statusPesanan.equalsIgnoreCase("DONE")) {
                    // Kalau sudah DONE, durasi tidak diupdate, bisa dilewati
                    continue; 
                }
                String idPesanan = model.getValueAt(i, 0).toString(); // Asumsi kolom 0 = id_pesanan
                
                // Ambil timestamp dari database
                Timestamp waktuDipesan = null;
                try (Connection con = Koneksi.getConnection();
                     PreparedStatement ps = con.prepareStatement("SELECT tanggal FROM pesanan WHERE id_pesanan = ?")) {
                    ps.setString(1, idPesanan);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        waktuDipesan = rs.getTimestamp("tanggal");
                    }
                }

                if (waktuDipesan != null) {
                    long diff = System.currentTimeMillis() - waktuDipesan.getTime();
                    long menit = diff / 60000;
                    long detik = (diff / 1000) % 60;
                    String durasi = String.format("%02dm %02ds", menit, detik);
                    model.setValueAt(durasi, i, 8); // kolom durasi
                } else {
                    model.setValueAt("N/A", i, 8);
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    });
    timer.start();
    }
    private void autorefresh(){
        Timer timer = new Timer(3000, e -> {
            StatusKasir_Model m = new StatusKasir_Model();
            DefaultTableModel model = m.getData();
            order.setModel(model);
            order.getColumnModel().getColumn(7).setMinWidth(0);
            order.getColumnModel().getColumn(7).setMaxWidth(0);
            order.getColumnModel().getColumn(7).setWidth(0);
        });
        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Menu;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable order;
    // End of variables declaration//GEN-END:variables
}
